# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3afcaf4848a074c49a30b64c408a4a7dfa03e05d53ef374839cabd2d669d9bcee1403b2c429da0d59305e98278ca549c3a3b0ec5fb6ac4a56a54a82c37f4b898

test:
  secret_key_base: b4be3e6dea219e7fde95d83a50623739309bc7cf76eec27a63516553751bf6b00473f2c2d5e2ea268ec608a8f4ece2f60dde1434287eebcea3d66773c1a28153

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
